/**
 * Claude Code 훅 연결
 * -------------------------------------------------------------
 * ~/.claude/settings.json 에 우리 훅을 넣고 뺀다.
 *
 * 훅 명령은 "스크립트 파일을 실행해라" 한 줄뿐이다. 실제 일은 userData 에 둔
 * claude-hook.ps1 이 한다 — Claude Code 가 stdin 으로 주는 JSON 을 바이트 그대로
 * 앱의 /claude 로 넘긴다. 그래서
 *  - 명령줄에 한글이 없다 (CP949 로 깨질 일이 없다)
 *  - Node 가 없는 PC 에서도 된다 (윈도우 기본 PowerShell 5.1)
 *  - 동작을 바꿀 땐 스크립트만 새로 쓰면 되고 settings.json 은 다시 안 건드린다
 *
 * 우리 훅은 명령에 'deskpet' 이 들어 있는 것으로 알아본다. 예전 방식
 * (node .../deskpet/tools/say.js) 도 여기에 걸려서 연결할 때 새 방식으로 바뀐다.
 * 다른 훅은 건드리지 않는다.
 *
 * electron 을 쓰지 않는다 — 경로를 인자로 받아서 node 만으로 시험할 수 있다.
 */
const fs = require('fs');
const path = require('path');
const os = require('os');

/**
 * 훅을 걸 이벤트. matcher 없이 건다 (Notification 은 모든 알림 종류가 온다 — 고르는 건 앱이 한다).
 * StopFailure = API 오류 등으로 응답이 끊겼을 때. SessionStart · SessionEnd = 세션 목록(메뉴) 관리.
 */
const EVENTS = ['SessionStart', 'UserPromptSubmit', 'Stop', 'StopFailure', 'Notification', 'SessionEnd'];

const MARK = 'deskpet';

const defaultSettingsPath = () => path.join(os.homedir(), '.claude', 'settings.json');

/**
 * 훅 스크립트 — stdin 바이트를 그대로 POST 한다.
 * $input · Read-Host 는 콘솔 코드페이지(CP949)로 디코드해서 한글이 깨지므로 표준 입력 스트림을 직접 읽는다.
 * 앱이 꺼져 있거나 멈춰 있어도 Claude Code 를 막지 않게 짧은 타임아웃 + 오류 무시.
 */
function hookScript(port) {
  const base = 'http://127.0.0.1:' + port;
  return [
    '# DeskPet - Claude Code hook (generated by DeskPet, do not edit)',
    '# Forwards the hook JSON from stdin to the DeskPet app as raw UTF-8 bytes.',
    '# If the app does not know this session\'s terminal window yet, it answers needWindow',
    '# and we walk up the process tree once to find it (so a click can bring it to front).',
    'function Post($url, $bytes) {',
    '  $req = [System.Net.HttpWebRequest]::Create($url)',
    "  $req.Method = 'POST'",
    "  $req.ContentType = 'application/json; charset=utf-8'",
    '  $req.Timeout = 1500',
    '  $req.ReadWriteTimeout = 1500',
    '  $req.ContentLength = $bytes.Length',
    '  $out = $req.GetRequestStream()',
    '  $out.Write($bytes, 0, $bytes.Length)',
    '  $out.Close()',
    '  $res = $req.GetResponse()',
    '  $rd = New-Object System.IO.StreamReader($res.GetResponseStream())',
    '  $txt = $rd.ReadToEnd()',
    '  $res.Close()',
    '  return $txt',
    '}',
    'function Find-Window {',
    '  $all = @{}',
    '  foreach ($p in (Get-CimInstance Win32_Process -Property ProcessId, ParentProcessId, Name)) { $all[[int]$p.ProcessId] = $p }',
    "  $skip = @('explorer.exe', 'svchost.exe', 'services.exe', 'sihost.exe', 'wininit.exe')",
    '  $chain = @()',
    '  $cur = $PID',
    '  for ($i = 0; $i -lt 20 -and $all.ContainsKey($cur); $i++) {',
    '    $e = $all[$cur]',
    '    if ($skip -contains $e.Name) { break }',
    '    $chain += $cur',
    '    $h = 0',
    '    try { $h = [Diagnostics.Process]::GetProcessById($cur).MainWindowHandle } catch { }',
    "    if ($h -ne 0) { return @{ pid = $cur; hwnd = [int64]$h; name = $e.Name } }",
    '    $cur = [int]$e.ParentProcessId',
    '  }',
    '  # classic console: the window belongs to a conhost child of one of the shells',
    '  foreach ($c in $chain) {',
    "    foreach ($k in ($all.Values | Where-Object { $_.ParentProcessId -eq $c -and ($_.Name -eq 'conhost.exe' -or $_.Name -eq 'OpenConsole.exe') })) {",
    '      $h = 0',
    '      try { $h = [Diagnostics.Process]::GetProcessById([int]$k.ProcessId).MainWindowHandle } catch { }',
    "      if ($h -ne 0) { return @{ pid = [int]$k.ProcessId; hwnd = [int64]$h; name = $k.Name } }",
    '    }',
    '  }',
    '  return $null',
    '}',
    'try {',
    '  # App not running: Windows retries a refused connect for ~2s, so probe with a short wait first',
    '  $tc = New-Object System.Net.Sockets.TcpClient',
    "  $ar = $tc.BeginConnect('127.0.0.1', " + port + ', $null, $null)',
    '  $up = $ar.AsyncWaitHandle.WaitOne(300) -and $tc.Connected',
    '  $tc.Close()',
    '  if (-not $up) { exit 0 }',
    '  $in = [Console]::OpenStandardInput()',
    '  $ms = New-Object System.IO.MemoryStream',
    '  $in.CopyTo($ms)',
    '  $body = $ms.ToArray()',
    "  $ans = Post '" + base + "/claude' $body",
    "  if ($ans -match '\"needWindow\":\"([^\"]+)\"') {",
    '    $sid = $Matches[1]',
    '    $w = Find-Window',
    '    if ($w) {',
    "      $j = '{\"session_id\":\"' + $sid + '\",\"pid\":' + $w.pid + ',\"hwnd\":' + $w.hwnd + ',\"name\":\"' + $w.name + '\"}'",
    "      [void](Post '" + base + "/claude-window' ([Text.Encoding]::UTF8.GetBytes($j)))",
    '    }',
    '  }',
    '} catch { }',
    'exit 0',
    '',
  ].join('\r\n');
}

/** settings.json 에 들어갈 명령 — bash 로 돌든 PowerShell 로 돌든 똑같이 동작한다 */
function hookCommand(scriptPath) {
  return 'powershell -NoProfile -ExecutionPolicy Bypass -File "' + scriptPath.replace(/\\/g, '/') + '"';
}

const isOurs = (h) => h && typeof h.command === 'string' && h.command.toLowerCase().includes(MARK);

function readSettings(file) {
  if (!fs.existsSync(file)) return {};
  const raw = fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, '');
  if (!raw.trim()) return {};
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error('settings.json 을 읽을 수 없어서 손대지 않았다 (' + e.message + ')');
  }
}

function writeSettings(file, obj) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (fs.existsSync(file)) fs.copyFileSync(file, file + '.deskpet-bak');
  const tmp = file + '.deskpet-tmp';
  fs.writeFileSync(tmp, JSON.stringify(obj, null, 2) + '\n', 'utf8');
  fs.renameSync(tmp, file);
}

/** 이벤트 목록에서 우리 훅만 빼고, 비어 버린 그룹은 지운다 */
function stripOurs(groups) {
  return (groups || [])
    .map((g) => ({ ...g, hooks: (g.hooks || []).filter((h) => !isOurs(h)) }))
    .filter((g) => g.hooks.length);
}

/**
 * 지금 상태.
 * connected: 세 이벤트 모두 우리 훅이 지금 스크립트를 부르고 있다
 * legacy: 예전 방식(say.js 등) 우리 훅이 남아 있다
 */
function status({ settingsPath = defaultSettingsPath(), scriptPath } = {}) {
  let cfg;
  try {
    cfg = readSettings(settingsPath);
  } catch (e) {
    return { connected: false, error: e.message, settingsPath };
  }
  const want = scriptPath ? hookCommand(scriptPath) : null;
  const hooks = cfg.hooks || {};
  let current = 0;
  let legacy = 0;
  for (const [ev, groups] of Object.entries(hooks)) {
    for (const g of groups || []) {
      for (const h of g.hooks || []) {
        if (!isOurs(h)) continue;
        if (EVENTS.includes(ev) && h.command === want) current++;
        else legacy++;
      }
    }
  }
  const scriptOk = !!scriptPath && fs.existsSync(scriptPath);
  return { connected: current >= EVENTS.length && scriptOk, legacy, settingsPath };
}

/** 연결 — 스크립트를 쓰고, 우리 훅을 새로 건다 (이미 있으면 교체, 중복 없음) */
function install({ settingsPath = defaultSettingsPath(), scriptPath, port }) {
  const cfg = readSettings(settingsPath);     // 못 읽으면 여기서 멈춘다 (아무것도 안 씀)

  fs.mkdirSync(path.dirname(scriptPath), { recursive: true });
  fs.writeFileSync(scriptPath, hookScript(port), 'utf8');

  const hooks = { ...(cfg.hooks || {}) };
  // 예전 방식 포함, 모든 이벤트에서 우리 훅을 먼저 걷어낸다
  for (const ev of Object.keys(hooks)) {
    const left = stripOurs(hooks[ev]);
    if (left.length) hooks[ev] = left; else delete hooks[ev];
  }
  const cmd = hookCommand(scriptPath);
  for (const ev of EVENTS) {
    hooks[ev] = (hooks[ev] || []).concat([{ hooks: [{ type: 'command', command: cmd, timeout: 5 }] }]);
  }
  writeSettings(settingsPath, { ...cfg, hooks });
  return status({ settingsPath, scriptPath });
}

/** 연결 끊기 — 우리 훅만 뺀다 */
function uninstall({ settingsPath = defaultSettingsPath(), scriptPath } = {}) {
  const cfg = readSettings(settingsPath);
  if (!cfg.hooks) return status({ settingsPath, scriptPath });
  const hooks = { ...cfg.hooks };
  for (const ev of Object.keys(hooks)) {
    const left = stripOurs(hooks[ev]);
    if (left.length) hooks[ev] = left; else delete hooks[ev];
  }
  const next = { ...cfg };
  if (Object.keys(hooks).length) next.hooks = hooks; else delete next.hooks;
  writeSettings(settingsPath, next);
  return status({ settingsPath, scriptPath });
}

module.exports = { EVENTS, status, install, uninstall, hookScript, hookCommand, defaultSettingsPath };
