/**
 * 앱이 userData 에 써 두는 PowerShell 스크립트들
 * -------------------------------------------------------------
 * 윈도우 기본 PowerShell 5.1 로 돈다 (Node 가 없는 PC 에서도).
 * 한글이 든 스크립트는 UTF-8 BOM 을 붙여서 쓴다 — PS 5.1 은 BOM 이 없으면 ANSI(CP949)로 읽는다.
 *
 *  deskpet-focus.ps1  세션의 터미널 창을 앞으로 (main.js focusClaudeSession)
 *  deskpet.ps1        명령줄 도구 — say / run / watch (빌드 · 서버 기동 알림)
 */

/** 창 핸들을 받아 앞으로 가져온다. 결과를 ok | denied | gone 으로 찍는다 */
function focusScript() {
  return [
    'param([string]$Hwnd)',
    "Add-Type -TypeDefinition @'",
    'using System;',
    'using System.Runtime.InteropServices;',
    'public static class DeskPetWin {',
    '  [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr h);',
    '  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr h);',
    '  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr h, int n);',
    '  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);',
    '  [DllImport("user32.dll")] public static extern void keybd_event(byte vk, byte scan, uint flags, UIntPtr extra);',
    '  [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();',
    '  [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h, IntPtr pid);',
    '  [DllImport("kernel32.dll")] public static extern uint GetCurrentThreadId();',
    '  [DllImport("user32.dll")] public static extern bool AttachThreadInput(uint a, uint b, bool attach);',
    '  [DllImport("user32.dll")] public static extern bool BringWindowToTop(IntPtr h);',
    '  [StructLayout(LayoutKind.Sequential)] public struct FLASHWINFO { public uint cbSize; public IntPtr hwnd; public uint dwFlags; public uint uCount; public uint dwTimeout; }',
    '  [DllImport("user32.dll")] public static extern bool FlashWindowEx(ref FLASHWINFO f);',
    '}',
    "'@",
    '$h = [IntPtr][int64]$Hwnd',
    "if (-not [DeskPetWin]::IsWindow($h)) { 'gone'; exit }",
    'if ([DeskPetWin]::IsIconic($h)) { [void][DeskPetWin]::ShowWindow($h, 9) }',
    '# 1) Windows blocks background processes from stealing focus; holding ALT is the usual way around it',
    '[DeskPetWin]::keybd_event(0x12, 0, 0, [UIntPtr]::Zero)',
    '[void][DeskPetWin]::SetForegroundWindow($h)',
    '[DeskPetWin]::keybd_event(0x12, 0, 2, [UIntPtr]::Zero)',
    "if ([DeskPetWin]::GetForegroundWindow() -eq $h) { 'ok'; exit }",
    '# 2) attach to the current foreground thread and try again',
    '$fg = [DeskPetWin]::GetForegroundWindow()',
    '$a = [DeskPetWin]::GetWindowThreadProcessId($fg, [IntPtr]::Zero)',
    '$me = [DeskPetWin]::GetCurrentThreadId()',
    '[void][DeskPetWin]::AttachThreadInput($me, $a, $true)',
    '[void][DeskPetWin]::BringWindowToTop($h)',
    '[void][DeskPetWin]::SetForegroundWindow($h)',
    '[void][DeskPetWin]::AttachThreadInput($me, $a, $false)',
    "if ([DeskPetWin]::GetForegroundWindow() -eq $h) { 'ok2'; exit }",
    '# 3) still blocked - flash its taskbar button so the user can see which window',
    '$f = New-Object DeskPetWin+FLASHWINFO',
    '$f.cbSize = [Runtime.InteropServices.Marshal]::SizeOf($f); $f.hwnd = $h; $f.dwFlags = 3 -bor 12; $f.uCount = 5; $f.dwTimeout = 0',
    '[void][DeskPetWin]::FlashWindowEx([ref]$f)',
    "'flash'",
    '',
  ].join('\r\n');
}

/**
 * 명령줄 도구. 사용법은 스크립트 첫머리 주석과 README "빌드 · 서버 알림" 참고.
 *   deskpet.ps1 say "빌드 끝났어" -Mood happy
 *   deskpet.ps1 run "mvn -q package" -Name 빌드
 *   deskpet.ps1 watch C:\tomcat\logs\catalina.out -Name 톰캣
 */
function cliScript(port) {
  return '\uFEFF' + [
    '<#',
    '  DeskPet 명령줄 도구 (앱이 만든 파일 — 앱을 켤 때마다 새로 쓴다. 고치지 말 것)',
    '',
    '  say   "할 말" [-Mood normal|happy|alert|fail]',
    '  run   "명령" [-Name 이름]     명령을 돌리고 끝나면 성공/실패와 걸린 시간을 알려 준다 (종료 코드 그대로 돌려줌)',
    '  watch 로그파일 [-Name 이름] [-Ok 정규식] [-Fail 정규식]',
    '        로그에 새로 붙는 줄을 지켜보다가 Ok 에 걸리면 "다 떴어", Fail 에 걸리면 쓰러지며 알려 주고 끝난다',
    '        기본값은 톰캣 · 스프링 부트 기동 메시지',
    '',
    '  todo  "할 일" [-Detail 설명] [-Date today|tomorrow|YYYY-MM-DD] [-Category 분류] [-Due HH:MM] [-Backlog] [-Repeat 평일]',
    '        DeskPet 할 일에 넣는다. 여러 줄이면 첫 줄이 제목, 나머지는 설명',
    '  note  "메모" [-Color yellow|pink|green|blue|gray]     스티커 메모로 붙인다',
    '        todo · note 는 -FromFile 경로(UTF-8 텍스트)로 내용을 넘길 수도 있다 — 긴 글 · 여러 줄은 이쪽이 안전',
    '',
    '  앱이 꺼져 있으면 say · run · watch 는 알림만 조용히 건너뛴다.',
    '  todo · note 는 앱이 꺼져 있으면 종료 코드 3 (그때는 todo.md 를 직접 고칠 것)',
    '#>',
    'param(',
    "  [Parameter(Position = 0)][string]$Command = 'help',",
    '  [Parameter(Position = 1)][string]$Target = \'\',',
    "  [string]$Mood = 'normal',",
    "  [string]$Name = '',",
    "  [string]$Detail = '',",
    "  [string]$Date = '',",
    "  [string]$Category = '',",
    "  [string]$Due = '',",
    "  [string]$Repeat = '',",
    "  [string]$Color = '',",
    "  [string]$FromFile = '',",
    '  [switch]$Backlog,',
    "  [string]$Ok = 'Server startup in|Started .+ in [0-9.]+ seconds',",
    "  [string]$Fail = 'startup failed|failed to start|Address already in use|BindException|OutOfMemoryError'",
    ')',
    '',
    '# $Src 가 있으면 알림 카드로 뜬다 (출처 이름 · $Lv = done | fail — 카드 색, fail 은 윈도우 알림도)',
    "function Send-Pet([string]$Text, [string]$M, [string]$Src = '', [string]$Lv = '') {",
    '  try {',
    '    $tc = New-Object System.Net.Sockets.TcpClient',
    "    $ar = $tc.BeginConnect('127.0.0.1', " + port + ', $null, $null)',
    '    $up = $ar.AsyncWaitHandle.WaitOne(300) -and $tc.Connected',
    '    $tc.Close()',
    '    if (-not $up) { return }',
    '    $o = @{ text = $Text; mood = $M }',
    '    if ($Src) { $o.source = $Src; $o.level = $Lv }',
    '    $json = $o | ConvertTo-Json -Compress',
    '    $bytes = [Text.Encoding]::UTF8.GetBytes($json)',
    "    $req = [System.Net.HttpWebRequest]::Create('http://127.0.0.1:" + port + "/say')",
    "    $req.Method = 'POST'",
    "    $req.ContentType = 'application/json; charset=utf-8'",
    '    $req.Timeout = 1500',
    '    $req.ContentLength = $bytes.Length',
    '    $out = $req.GetRequestStream()',
    '    $out.Write($bytes, 0, $bytes.Length)',
    '    $out.Close()',
    '    $req.GetResponse().Close()',
    '  } catch { }',
    '}',
    '',
    '# 할 일 · 메모 넣기 — 응답(JSON)을 돌려준다. 앱이 꺼져 있으면 $null',
    'function Post-Pet([string]$Path, $Obj) {',
    '  $tc = New-Object System.Net.Sockets.TcpClient',
    '  try {',
    "    $ar = $tc.BeginConnect('127.0.0.1', " + port + ', $null, $null)',
    '    $up = $ar.AsyncWaitHandle.WaitOne(500) -and $tc.Connected',
    '  } catch { $up = $false } finally { $tc.Close() }',
    '  if (-not $up) { return $null }',
    '  $bytes = [Text.Encoding]::UTF8.GetBytes(($Obj | ConvertTo-Json -Compress))',
    "  $req = [System.Net.HttpWebRequest]::Create('http://127.0.0.1:" + port + "' + $Path)",
    "  $req.Method = 'POST'",
    "  $req.ContentType = 'application/json; charset=utf-8'",
    '  $req.Timeout = 5000',
    '  $req.ContentLength = $bytes.Length',
    '  $out = $req.GetRequestStream(); $out.Write($bytes, 0, $bytes.Length); $out.Close()',
    '  try { $resp = $req.GetResponse() } catch [System.Net.WebException] { $resp = $_.Exception.Response }',
    '  if (-not $resp) { return $null }',
    '  $sr = New-Object IO.StreamReader($resp.GetResponseStream(), [Text.Encoding]::UTF8)',
    '  $txt = $sr.ReadToEnd(); $sr.Close(); $resp.Close()',
    '  return ($txt | ConvertFrom-Json)',
    '}',
    '',
    '# 넣을 글 — -FromFile 이 있으면 그 파일(UTF-8), 없으면 두 번째 인자',
    'function Get-Body {',
    '  if ($FromFile) {',
    "    if (-not (Test-Path -LiteralPath $FromFile)) { Write-Host \"파일이 없어: $FromFile\"; exit 2 }",
    '    return [IO.File]::ReadAllText((Resolve-Path -LiteralPath $FromFile), [Text.Encoding]::UTF8)',
    '  }',
    '  return $Target',
    '}',
    '',
    'function Format-Dur([TimeSpan]$d) {',
    "  if ($d.TotalMinutes -ge 1) { return ('{0}분 {1}초' -f [int][math]::Floor($d.TotalMinutes), $d.Seconds) }",
    "  return ('{0}초' -f [int][math]::Round($d.TotalSeconds))",
    '}',
    '',
    'switch ($Command) {',
    "  'say' {",
    '    Send-Pet $Target $Mood',
    '  }',
    "  'run' {",
    "    if (-not $Target) { Write-Host '사용법: deskpet.ps1 run \"명령\" [-Name 이름]'; exit 2 }",
    '    if (-not $Name) { $Name = ($Target -split \' \')[0] }',
    '    $t0 = Get-Date',
    '    & cmd.exe /c $Target',
    '    $code = $LASTEXITCODE',
    '    $dur = Format-Dur ((Get-Date) - $t0)',
    "    if ($code -eq 0) { Send-Pet \"끝났어 ($dur)\" 'happy' $Name 'done' }",
    "    else { Send-Pet \"실패 — 코드 $code ($dur)\" 'fail' $Name 'fail' }",
    '    exit $code',
    '  }',
    "  'watch' {",
    "    if (-not $Target) { Write-Host '사용법: deskpet.ps1 watch 로그파일 [-Name 이름]'; exit 2 }",
    '    if (-not $Name) { $Name = [IO.Path]::GetFileNameWithoutExtension($Target) }',
    "    Write-Host \"[$Name] 지켜보는 중: $Target  (그만두려면 Ctrl+C)\"",
    '    while (-not (Test-Path $Target)) { Start-Sleep -Seconds 1 }',
    '    $t0 = Get-Date',
    '    Get-Content -Path $Target -Tail 0 -Wait | ForEach-Object {',
    '      if ($_ -match $Fail) {',
    '        $line = $_.Trim()',
    '        if ($line.Length -gt 60) { $line = $line.Substring(0, 60) + \'…\' }',
    "        Send-Pet \"기동 실패 — $line\" 'fail' $Name 'fail'",
    "        Write-Host \"[$Name] 실패 감지: $_\"",
    '        exit 1',
    '      }',
    '      if ($_ -match $Ok) {',
    '        $dur = Format-Dur ((Get-Date) - $t0)',
    "        Send-Pet \"다 떴어! ($dur)\" 'happy' $Name 'done'",
    "        Write-Host \"[$Name] 성공 감지: $_\"",
    '        exit 0',
    '      }',
    '    }',
    '  }',
    "  { $_ -in 'todo', 'note' } {",
    '    # 결과 글을 UTF-8 로 — Git Bash · Claude Code 에서 불러도 한글이 안 깨지게 (run 은 자식 명령 출력 때문에 건드리지 않는다)',
    '    try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }',
    '    $text = Get-Body',
    "    if (-not $text -or -not $text.Trim()) { Write-Host '사용법: deskpet.ps1 todo \"할 일\" | deskpet.ps1 note \"메모\" (또는 -FromFile 경로)'; exit 2 }",
    '    $o = @{ text = $text }',
    "    if ($Command -eq 'todo') {",
    '      if ($Detail) { $o.detail = $Detail }',
    '      if ($Date) { $o.date = $Date }',
    '      if ($Category) { $o.category = $Category }',
    '      if ($Due) { $o.due = $Due }',
    '      if ($Repeat) { $o.repeat = $Repeat }',
    '      if ($Backlog) { $o.backlog = $true }',
    '    } elseif ($Color) { $o.color = $Color }',
    "    $r = Post-Pet ('/' + $Command) $o",
    "    if ($null -eq $r) { Write-Host \"DeskPet 이 꺼져 있어 — 넣지 못했어 (할 일 파일: $env:APPDATA\\deskpet\\todo.md)\"; exit 3 }",
    "    if (-not $r.ok) { Write-Host ('못 넣었어: ' + $r.error); exit 1 }",
    "    if ($Command -eq 'todo') { Write-Host ('할 일에 넣었어 — ' + $r.title + ' (' + $r.where + ')') } else { Write-Host '스티커 메모로 붙였어' }",
    '  }',
    '  default {',
    "    Write-Host 'deskpet.ps1 say \"할 말\" [-Mood happy|alert|fail]'",
    "    Write-Host 'deskpet.ps1 todo \"할 일\" [-Detail 설명] [-Date today|tomorrow|YYYY-MM-DD] [-Category 분류] [-Due HH:MM] [-Backlog] [-Repeat 평일] [-FromFile 경로]'",
    "    Write-Host 'deskpet.ps1 note \"메모\" [-Color yellow|pink|green|blue|gray] [-FromFile 경로]'",
    "    Write-Host 'deskpet.ps1 run \"명령\" [-Name 이름]'",
    "    Write-Host 'deskpet.ps1 watch 로그파일 [-Name 이름] [-Ok 정규식] [-Fail 정규식]'",
    '  }',
    '}',
    '',
  ].join('\r\n');
}

module.exports = { focusScript, cliScript };
